packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
catalog:
  "@better-auth/cli": 1.4.7
  "@internationalized/date": 3.10.0
  embla-carousel-react: 8.6.0
  "@biomejs/biome": 2.3.9
  "@radix-ui/react-avatar": 1.1.11
  "@radix-ui/react-collapsible": 1.1.12
  "@radix-ui/react-dialog": 1.1.15
  "@radix-ui/react-dropdown-menu": 2.1.16
  "@radix-ui/react-label": 2.1.8
  "@radix-ui/react-separator": 1.1.8
  "@radix-ui/react-slot": 1.2.4
  "@radix-ui/react-tooltip": 1.2.8
  "@supabase/supabase-js": 2.87.3
  "@tailwindcss/typography": 0.5.19
  "@tailwindcss/vite": 4.1.18
  "@tanstack/devtools-vite": 0.3.12
  "@tanstack/react-devtools": 0.8.4
  "@tanstack/react-form": 1.27.4
  "@tanstack/react-query": 5.90.12
  "@tanstack/react-query-devtools": 5.91.1
  "@tanstack/react-router": 1.141.2
  "@tanstack/react-router-ssr-query": 1.141.2
  "@tanstack/react-start": 1.141.3
  "@tanstack/react-store": 0.8.0
  "@tanstack/react-table": 8.21.3
  "@tanstack/zod-adapter": 1.141.2
  "@types/lodash-es": 4.17.12
  "@types/node": 25.0.2
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 5.1.2
  "@vitejs/plugin-react-oxc": 0.4.3
  babel-plugin-react-compiler: 1.0.0
  better-auth: 1.4.7
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  dotenv: 17.2.3
  dotenv-cli: 11.0.0
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  input-otp: 1.4.2
  lodash-es: 4.17.21
  lucide-react: 0.561.0
  next-themes: 0.4.6
  nitro: 3.0.1-alpha.1
  pino: 10.1.0
  pino-pretty: 13.1.3
  postgres: 3.4.7
  radix-ui: 1.4.3
  react: 19.2.3
  react-aria-components: 1.13.0
  react-day-picker: 9.12.0
  react-dom: 19.2.3
  react-icons: 5.5.0
  react-resizable-panels: 3.0.6
  recharts: 3.6.0
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tsx: 4.21.0
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  uuid: 13.0.0
  vaul: 1.1.2
  vite: 7.3.0
  vite-tsconfig-paths: 6.0.1
  vitest: 4.0.16
  zod: 4.2.1

overrides:
  vite: ^8.0.0-beta.2